INFO:__main__:Loading FB15k237 dataset...
INFO:__main__:Using original training dataset (no artificial triples)
WARNING:pykeen.triples.triples_factory:You're trying to map triples with 30 entities and 0 relations that are not in the training set. These triples will be excluded from the mapping.
WARNING:pykeen.triples.triples_factory:In total 28 from 20466 triples were filtered out
INFO:__main__:Computing triple weights using Leave-One-Out scoring...
INFO:__main__:Converting triples to string format...
INFO:__main__:Converted 272115 triples to string format
INFO:leave_one_out_scoring:Scoring 272115 triples...
INFO:leave_one_out_scoring:Building entity properties map...
INFO:leave_one_out_scoring:Built properties map for 14505 entities
INFO:leave_one_out_scoring:Scored 1000/272115 triples
WARNING:leave_one_out_scoring:API call attempt 1 failed: HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=30.0)
INFO:leave_one_out_scoring:Scored 2000/272115 triples
INFO:leave_one_out_scoring:Scored 3000/272115 triples
INFO:leave_one_out_scoring:Scored 4000/272115 triples
INFO:leave_one_out_scoring:Scored 5000/272115 triples
INFO:leave_one_out_scoring:Scored 6000/272115 triples
INFO:leave_one_out_scoring:Scored 7000/272115 triples
INFO:leave_one_out_scoring:Scored 8000/272115 triples
INFO:leave_one_out_scoring:Scored 9000/272115 triples
INFO:leave_one_out_scoring:Scored 10000/272115 triples
INFO:leave_one_out_scoring:Scored 11000/272115 triples
INFO:leave_one_out_scoring:Scored 12000/272115 triples
INFO:leave_one_out_scoring:Scored 13000/272115 triples
INFO:leave_one_out_scoring:Scored 14000/272115 triples
INFO:leave_one_out_scoring:Scored 15000/272115 triples
INFO:leave_one_out_scoring:Scored 16000/272115 triples
INFO:leave_one_out_scoring:Scored 17000/272115 triples
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Users\Slawek\anaconda3\envs\knowledge_graphs\lib\linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
  File "C:\Users\Slawek\anaconda3\envs\knowledge_graphs\lib\linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
  File "C:\Users\Slawek\anaconda3\envs\knowledge_graphs\lib\tokenize.py", line 394, in open
    buffer = _builtin_open(filename, 'rb')
KeyboardInterrupt

Original exception was:
Traceback (most recent call last):
  File "C:\Users\Slawek\Documents\GitHub\link-prediction-thesis\pre-training\weigthed_training\complex_weighted_training_pipeline.py", line 617, in <module>
    main()
  File "C:\Users\Slawek\Documents\GitHub\link-prediction-thesis\pre-training\weigthed_training\complex_weighted_training_pipeline.py", line 599, in main
    results = train_weighted_complex_pipeline(config)
  File "C:\Users\Slawek\Documents\GitHub\link-prediction-thesis\pre-training\weigthed_training\complex_weighted_training_pipeline.py", line 432, in train_weighted_complex_pipeline
    triple_weights = compute_and_save_triple_weights(
  File "C:\Users\Slawek\Documents\GitHub\link-prediction-thesis\pre-training\weigthed_training\complex_weighted_training_pipeline.py", line 353, in compute_and_save_triple_weights
    string_weights = scorer.score_all_triples(
  File "C:\Users\Slawek\Documents\GitHub\link-prediction-thesis\pre-training\weigthed_training\leave_one_out_scoring.py", line 308, in score_all_triples
    score = self.get_triple_score_averaged(head, relation, tail)
  File "C:\Users\Slawek\Documents\GitHub\link-prediction-thesis\pre-training\weigthed_training\leave_one_out_scoring.py", line 256, in get_triple_score_averaged
    head_score = self.get_triple_score_from_head(head, relation, tail)
  File "C:\Users\Slawek\Documents\GitHub\link-prediction-thesis\pre-training\weigthed_training\leave_one_out_scoring.py", line 180, in get_triple_score_from_head
    recommendations = self._call_recommender_api(properties_list)
  File "C:\Users\Slawek\Documents\GitHub\link-prediction-thesis\pre-training\weigthed_training\leave_one_out_scoring.py", line 79, in _call_recommender_api
    response = requests.post(
  File "C:\Users\Slawek\anaconda3\envs\knowledge_graphs\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\Slawek\anaconda3\envs\knowledge_graphs\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Slawek\anaconda3\envs\knowledge_graphs\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Slawek\anaconda3\envs\knowledge_graphs\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Slawek\anaconda3\envs\knowledge_graphs\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\Slawek\anaconda3\envs\knowledge_graphs\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "C:\Users\Slawek\anaconda3\envs\knowledge_graphs\lib\site-packages\urllib3\connectionpool.py", line 493, in _make_request
    conn.request(
  File "C:\Users\Slawek\anaconda3\envs\knowledge_graphs\lib\site-packages\urllib3\connection.py", line 445, in request
    self.endheaders()
  File "C:\Users\Slawek\anaconda3\envs\knowledge_graphs\lib\http\client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Slawek\anaconda3\envs\knowledge_graphs\lib\http\client.py", line 1038, in _send_output
    self.send(msg)
  File "C:\Users\Slawek\anaconda3\envs\knowledge_graphs\lib\http\client.py", line 976, in send
    self.connect()
  File "C:\Users\Slawek\anaconda3\envs\knowledge_graphs\lib\site-packages\urllib3\connection.py", line 276, in connect
    self.sock = self._new_conn()
  File "C:\Users\Slawek\anaconda3\envs\knowledge_graphs\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\Slawek\anaconda3\envs\knowledge_graphs\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
KeyboardInterrupt
